backend:
  name: git-gateway
  repo: senegalx/binoks-v2 # Path to your Github repository
  branch: main # Branch to update (master by default)

media_folder: "public/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

logo_url: /images/logo.png

slug: { { slug } }

collections: # A list of collections the CMS should be able to edit
  - label: Pages
    name: pages
    files:
      - label: Accueil
        name: homepage
        file: /src/content/homepage/index.md
        fields:
          - {label: "Bannière", name: "banner", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Contenu", name: "content", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Label du bouton", name: "button.label", widget: "string"},
                {label: "Lien du bouton", name: "button.link", widget: "string"},
                {label: "Activation du bouton", name: "button.enable", widget: "boolean"},
              ]
            }
          # - {label: "Titre de la section 'Fonctionnalités'", name: "feature.title", widget: "string"}
          # - {label: "Fonctionnalités", name: "feature.features", widget: "list", fields: [
          #     {label: "Nom de la fonctionnalité", name: "name", widget: "string"},
          #     {label: "Icône de la fonctionnalité", name: "icon", widget: "image"},
          #     {label: "Contenu de la fonctionnalité", name: "content", widget: "text"}
          #   ]}
          # - {label: "Titre de la section 'Services'", name: "services.title", widget: "string"}
          # - {label: "Services", name: "services.services", widget: "list", fields: [
          #     {label: "Titre du service", name: "title", widget: "string"},
          #     {label: "Couleur du texte", name: "color", widget: "string"},
          #     {label: "Contenu du service", name: "content", widget: "text"},
          #     {label: "Images du service", name: "images", widget: "list", field: {widget: "image"}},
          #     {label: "Bouton du service", name: "button", widget: "object", fields: [
          #       {label: "Activation du bouton", name: "enable", widget: "boolean"},
          #       {label: "Label du bouton", name: "label", widget: "string"},
          #       {label: "Lien du bouton", name: "link", widget: "string"}
          #     ]}
          #   ]}
          # - {label: "Titre de la section 'Workflow'", name: "workflow.title", widget: "string"}
          # - {label: "Image du workflow", name: "workflow.image", widget: "image"}
          # - {label: "Description du workflow", name: "workflow.description", widget: "text"}
          # - {label: "Titre de l'appel à l'action", name: "call_to_action.title", widget: "string"}
          # - {label: "Contenu de l'appel à l'action", name: "call_to_action.content", widget: "text"}
          # - {label: "Image de l'appel à l'action", name: "call_to_action.image", widget: "image"}
          # - {label: "Bouton de l'appel à l'action", name: "call_to_action.button", widget: "object", fields: [
          #     {label: "Activation du bouton", name: "enable", widget: "boolean"},
          #     {label: "Label du bouton", name: "label", widget: "string"},
          #     {label: "Lien du bouton", name: "link", widget: "string"}
          #   ]}
      - label: contact
        name: contact
        file: /src/content/contact/index.md
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Brouillon", name: "draft", widget: "boolean" }
          - { label: "Info", name: "info", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Contacts", name: "contacts", widget: "list", fields: [
                  { label: "Contact", name: "contact", widget: "string" }
                ]
              }
            ]
          }
  - label: Actualités # Label used in the UI for the collection
    label_singular: blog # Label for singular post
    name: blog # Name of the collection used for various functionality in the CMS
    folder: /src/content/blog # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Brouillon", widget: "boolean" }
      - { name: "body", label: "Contenu", widget: "markdown" }