backend:
  name: git-gateway
  repo: senegalx/binoks-v2 # Path to your Github repository
  branch: main # Branch to update (master by default)

media_folder: "public/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

logo_url: /images/logo.png

slug: { { slug } }

collections: # A list of collections the CMS should be able to edit
  - label: Pages
    name: pages
    files:
      - label: Accueil
        name: homepage
        file: /src/content/homepage/index.md
        fields:
          - {label: "Bannière", name: "banner", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Contenu", name: "content", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Bouton", name: "button", widget: "object", collapsed: true,
                fields: [
                  {label: "Label", name: "label", widget: "string"},
                  {label: "Lien", name: "link", widget: "string"},
                  {label: "Activation", name: "enable", widget: "boolean"}]}
              ]
            }
          - {label: "Fonctionnalités", name: "feature", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Fonctionnalités", name: "features", widget: "list", fields: [
                  {label: "Nom", name: "name", widget: "string"},
                  {label: "Icône", name: "icon", widget: "image"},
                  {label: "Contenu", name: "content", widget: "text"}]}]
            }
          - {label: "Services", name: "services", widget: "list", fields: [
                  {label: "Titre", name: "title", widget: "string"},
                  {label: "Couleur", name: "color", widget: "string"},
                  {label: "Contenu", name: "content", widget: "text"},
                  {label: "Images", name: "images", widget: "list", field: {widget: "image", name: image}},
                  {label: "Bouton", name: "button", widget: "object", fields: [
                    {label: "Activation", name: "enable", widget: "boolean"},
                    {label: "Label", name: "label", widget: "string"},
                    {label: "Lien", name: "link", widget: "string"}
                  ]}]
            }
          - {label: "Workflow", name: "workflow", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Description", name: "description", widget: "text"}]
            }
          - {label: "Appel à l'action", name: "call_to_action", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Contenu", name: "content", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Bouton", name: "button", widget: "object", fields: [
                  {label: "Activation", name: "enable", widget: "boolean"},
                  {label: "Label", name: "label", widget: "string"},
                  {label: "Lien", name: "link", widget: "string"}
                ]}]
            }
      - label: À propos
        name: apropos
        file: /src/content/a-propos/index.md
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Brouillon", name: "draft", widget: "boolean" }
          - {label: "Mission", name: "mission", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Contenu", name: "content", widget: "text"}]
            }
          - {label: "Valeur", name: "valeur", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Valeurs", name: "valeurs", widget: "list", 
                  fields: [
                    {label: "Nom", name: "name", widget: "string"},
                    {label: "Icône", name: "icon", widget: "image"},
                    {label: "Contenu", name: "content", widget: "text"}]}]
            }
      - label: Services
        name: services
        file: /src/content/services/index.md
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - { label: "Brouillon", name: "draft", widget: "boolean" }
          - { label: "Bénéfices", name: "benefice", widget: "object", fields: [
              { label: "Titre", name: "titre", widget: "string" },
              { label: "Bénéfices", name: "benefices", widget: "list", fields: [
                  { label: "Titre", name: "titre", widget: "string" },
                  {label: "Contenu", name: "content", widget: "text"}]}]}
          - { name: "body", label: "Contenu", widget: "markdown" }
      - label: Modules
        name: modules
        file: /src/content/fonctionnalites/index.md
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - { label: "Brouillon", name: "draft", widget: "boolean" }
          - {label: "Fonctionnalités", name: "fonctionnalites", widget: "list", 
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Contenu", name: "answer", widget: "text"}]}
      - label: Tarifs
        name: tarifs
        file: /src/content/pricing/index.md
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - { label: "Brouillon", name: "draft", widget: "boolean" }
          - {label: "Plans", name: "plans", widget: "list", 
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Sous-titre", name: "subtitle", widget: "string"},
                {label: "Prix", name: "price", widget: "number"},
                {label: "Type", name: "type", widget: "string"},
                {label: "Fonctionnalités", name: "features", widget: "list", summary: "{{fields.feature}}", field: {name: "feature", widget: "string"}},
                {label: "Bouton", name: "button", widget: "object", fields: [
                  {label: "Label", name: "label", widget: "string"},
                  {label: "Lien", name: "link", widget: "string"}]}]}
          - {label: "Appel à l'action", name: "call_to_action", widget: "object", collapsed: true,
              fields: [
                {label: "Titre", name: "title", widget: "string"},
                {label: "Contenu", name: "content", widget: "text"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Bouton", name: "button", widget: "object", fields: [
                  {label: "Activation", name: "enable", widget: "boolean"},
                  {label: "Label", name: "label", widget: "string"},
                  {label: "Lien", name: "link", widget: "string"}
                ]}]
            }
      - label: Contact
        name: contact
        file: /src/content/contact/index.md
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Brouillon", name: "draft", widget: "boolean" }
          - { label: "Info", name: "info", widget: "object", fields: [
              { label: "Titre", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Contacts", name: "contacts", widget: "list", fields: [
                  { label: "Contact", name: "contact", widget: "string" }
                ]
              }
            ]
          }
  - label: Actualités # Label used in the UI for the collection
    label_singular: blog # Label for singular post
    name: blog # Name of the collection used for various functionality in the CMS
    folder: /src/content/blog # Where each new post with .md should be saved
    create: true # Allows users to create new items in the collection
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Brouillon", widget: "boolean" }
      - { name: "body", label: "Contenu", widget: "markdown" }